# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/marty/Desktop/Kursinis/BoomChess

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/marty/Desktop/Kursinis/BoomChess

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/marty/Desktop/Kursinis/BoomChess/CMakeFiles /mnt/c/Users/marty/Desktop/Kursinis/BoomChess/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/marty/Desktop/Kursinis/BoomChess/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BoomChess

# Build rule for target.
BoomChess: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BoomChess
.PHONY : BoomChess

# fast build rule for target.
BoomChess/fast:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/build
.PHONY : BoomChess/fast

src/Board.o: src/Board.cpp.o

.PHONY : src/Board.o

# target to build an object file
src/Board.cpp.o:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/Board.cpp.o
.PHONY : src/Board.cpp.o

src/Board.i: src/Board.cpp.i

.PHONY : src/Board.i

# target to preprocess a source file
src/Board.cpp.i:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/Board.cpp.i
.PHONY : src/Board.cpp.i

src/Board.s: src/Board.cpp.s

.PHONY : src/Board.s

# target to generate assembly for a file
src/Board.cpp.s:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/Board.cpp.s
.PHONY : src/Board.cpp.s

src/Driver.o: src/Driver.cpp.o

.PHONY : src/Driver.o

# target to build an object file
src/Driver.cpp.o:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/Driver.cpp.o
.PHONY : src/Driver.cpp.o

src/Driver.i: src/Driver.cpp.i

.PHONY : src/Driver.i

# target to preprocess a source file
src/Driver.cpp.i:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/Driver.cpp.i
.PHONY : src/Driver.cpp.i

src/Driver.s: src/Driver.cpp.s

.PHONY : src/Driver.s

# target to generate assembly for a file
src/Driver.cpp.s:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/Driver.cpp.s
.PHONY : src/Driver.cpp.s

src/Evaluator.o: src/Evaluator.cpp.o

.PHONY : src/Evaluator.o

# target to build an object file
src/Evaluator.cpp.o:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/Evaluator.cpp.o
.PHONY : src/Evaluator.cpp.o

src/Evaluator.i: src/Evaluator.cpp.i

.PHONY : src/Evaluator.i

# target to preprocess a source file
src/Evaluator.cpp.i:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/Evaluator.cpp.i
.PHONY : src/Evaluator.cpp.i

src/Evaluator.s: src/Evaluator.cpp.s

.PHONY : src/Evaluator.s

# target to generate assembly for a file
src/Evaluator.cpp.s:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/Evaluator.cpp.s
.PHONY : src/Evaluator.cpp.s

src/FenParsing.o: src/FenParsing.cpp.o

.PHONY : src/FenParsing.o

# target to build an object file
src/FenParsing.cpp.o:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/FenParsing.cpp.o
.PHONY : src/FenParsing.cpp.o

src/FenParsing.i: src/FenParsing.cpp.i

.PHONY : src/FenParsing.i

# target to preprocess a source file
src/FenParsing.cpp.i:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/FenParsing.cpp.i
.PHONY : src/FenParsing.cpp.i

src/FenParsing.s: src/FenParsing.cpp.s

.PHONY : src/FenParsing.s

# target to generate assembly for a file
src/FenParsing.cpp.s:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/FenParsing.cpp.s
.PHONY : src/FenParsing.cpp.s

src/MoveGenerator.o: src/MoveGenerator.cpp.o

.PHONY : src/MoveGenerator.o

# target to build an object file
src/MoveGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/MoveGenerator.cpp.o
.PHONY : src/MoveGenerator.cpp.o

src/MoveGenerator.i: src/MoveGenerator.cpp.i

.PHONY : src/MoveGenerator.i

# target to preprocess a source file
src/MoveGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/MoveGenerator.cpp.i
.PHONY : src/MoveGenerator.cpp.i

src/MoveGenerator.s: src/MoveGenerator.cpp.s

.PHONY : src/MoveGenerator.s

# target to generate assembly for a file
src/MoveGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/MoveGenerator.cpp.s
.PHONY : src/MoveGenerator.cpp.s

src/Perft.o: src/Perft.cpp.o

.PHONY : src/Perft.o

# target to build an object file
src/Perft.cpp.o:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/Perft.cpp.o
.PHONY : src/Perft.cpp.o

src/Perft.i: src/Perft.cpp.i

.PHONY : src/Perft.i

# target to preprocess a source file
src/Perft.cpp.i:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/Perft.cpp.i
.PHONY : src/Perft.cpp.i

src/Perft.s: src/Perft.cpp.s

.PHONY : src/Perft.s

# target to generate assembly for a file
src/Perft.cpp.s:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/Perft.cpp.s
.PHONY : src/Perft.cpp.s

src/Piece.o: src/Piece.cpp.o

.PHONY : src/Piece.o

# target to build an object file
src/Piece.cpp.o:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/Piece.cpp.o
.PHONY : src/Piece.cpp.o

src/Piece.i: src/Piece.cpp.i

.PHONY : src/Piece.i

# target to preprocess a source file
src/Piece.cpp.i:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/Piece.cpp.i
.PHONY : src/Piece.cpp.i

src/Piece.s: src/Piece.cpp.s

.PHONY : src/Piece.s

# target to generate assembly for a file
src/Piece.cpp.s:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/Piece.cpp.s
.PHONY : src/Piece.cpp.s

src/Search.o: src/Search.cpp.o

.PHONY : src/Search.o

# target to build an object file
src/Search.cpp.o:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/Search.cpp.o
.PHONY : src/Search.cpp.o

src/Search.i: src/Search.cpp.i

.PHONY : src/Search.i

# target to preprocess a source file
src/Search.cpp.i:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/Search.cpp.i
.PHONY : src/Search.cpp.i

src/Search.s: src/Search.cpp.s

.PHONY : src/Search.s

# target to generate assembly for a file
src/Search.cpp.s:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/Search.cpp.s
.PHONY : src/Search.cpp.s

src/UCI.o: src/UCI.cpp.o

.PHONY : src/UCI.o

# target to build an object file
src/UCI.cpp.o:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/UCI.cpp.o
.PHONY : src/UCI.cpp.o

src/UCI.i: src/UCI.cpp.i

.PHONY : src/UCI.i

# target to preprocess a source file
src/UCI.cpp.i:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/UCI.cpp.i
.PHONY : src/UCI.cpp.i

src/UCI.s: src/UCI.cpp.s

.PHONY : src/UCI.s

# target to generate assembly for a file
src/UCI.cpp.s:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/UCI.cpp.s
.PHONY : src/UCI.cpp.s

src/ZobristKey.o: src/ZobristKey.cpp.o

.PHONY : src/ZobristKey.o

# target to build an object file
src/ZobristKey.cpp.o:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/ZobristKey.cpp.o
.PHONY : src/ZobristKey.cpp.o

src/ZobristKey.i: src/ZobristKey.cpp.i

.PHONY : src/ZobristKey.i

# target to preprocess a source file
src/ZobristKey.cpp.i:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/ZobristKey.cpp.i
.PHONY : src/ZobristKey.cpp.i

src/ZobristKey.s: src/ZobristKey.cpp.s

.PHONY : src/ZobristKey.s

# target to generate assembly for a file
src/ZobristKey.cpp.s:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/ZobristKey.cpp.s
.PHONY : src/ZobristKey.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/BoomChess.dir/build.make CMakeFiles/BoomChess.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... BoomChess"
	@echo "... src/Board.o"
	@echo "... src/Board.i"
	@echo "... src/Board.s"
	@echo "... src/Driver.o"
	@echo "... src/Driver.i"
	@echo "... src/Driver.s"
	@echo "... src/Evaluator.o"
	@echo "... src/Evaluator.i"
	@echo "... src/Evaluator.s"
	@echo "... src/FenParsing.o"
	@echo "... src/FenParsing.i"
	@echo "... src/FenParsing.s"
	@echo "... src/MoveGenerator.o"
	@echo "... src/MoveGenerator.i"
	@echo "... src/MoveGenerator.s"
	@echo "... src/Perft.o"
	@echo "... src/Perft.i"
	@echo "... src/Perft.s"
	@echo "... src/Piece.o"
	@echo "... src/Piece.i"
	@echo "... src/Piece.s"
	@echo "... src/Search.o"
	@echo "... src/Search.i"
	@echo "... src/Search.s"
	@echo "... src/UCI.o"
	@echo "... src/UCI.i"
	@echo "... src/UCI.s"
	@echo "... src/ZobristKey.o"
	@echo "... src/ZobristKey.i"
	@echo "... src/ZobristKey.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

